name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      uses: docker/setup-compose@v1
      with:
        version: 1.25.5

    - name: Run tests
      uses: docker/compose-action@v1
      with:
        context: .
        file: docker-compose.yml
        project-name: vessel-tracking
        command: rails tests
