name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Create DB
        run: docker-compose run web rails db:create
      - name: Run migrations
        run: docker-compose run web rails db:migrate                
      - name: Test
        run: docker-compose run web rails test   

